# Generated by Django 5.0.1 on 2026-03-29 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedVaultEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vault_key', models.CharField(max_length=120)),
                ('encrypted_value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vault Entry',
                'verbose_name_plural': 'Vault Entries',
                'unique_together': {('user', 'vault_key')},
            },
        ),
    ]
