# Generated by Django 5.0.1 on 2026-03-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        # 1. Drop the old unique constraint (user, vault_key) first
        migrations.AlterUniqueTogether(
            name='encryptedvaultentry',
            unique_together=set(),
        ),
        # 2. Add anon_key before removing the FK
        migrations.AddField(
            model_name='encryptedvaultentry',
            name='anon_key',
            field=models.CharField(db_index=True, default='00000000-0000-0000-0000-000000000000', max_length=36),
        ),
        # 3. Drop the old user FK
        migrations.RemoveField(
            model_name='encryptedvaultentry',
            name='user',
        ),
        # 4. Set new unique constraint
        migrations.AlterUniqueTogether(
            name='encryptedvaultentry',
            unique_together={('anon_key', 'vault_key')},
        ),
    ]
