from __future__ import annotations

import logging

from django.db import models

logger = logging.getLogger(__name__)


class EncryptedVaultEntry(models.Model):
    """
    Stores a single encrypted credential keyed by (anon_key, vault_key).

    ``anon_key`` is a UUID generated by the browser extension on first install
    and stored in chrome.storage.local.  It scopes vault entries per-browser
    without requiring user authentication.

    The ``encrypted_value`` column contains a token produced by
    ``vault.encryption.encrypt()`` — never a plaintext value.
    """

    # UUID generated by the extension — passed as X-Vault-Key request header
    anon_key = models.CharField(max_length=36, db_index=True, default="00000000-0000-0000-0000-000000000000")
    # Logical key — matches the required_user_data keys in ServiceMap
    # e.g. "national_id", "kra_pin", "nhif_number"
    vault_key = models.CharField(max_length=120)
    # AES-256-GCM ciphertext token (nonce.ciphertext in URL-safe base64)
    encrypted_value = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = [("anon_key", "vault_key")]
        verbose_name = "Vault Entry"
        verbose_name_plural = "Vault Entries"

    def __str__(self) -> str:
        # Never include the encrypted_value in __str__
        return f"VaultEntry(anon_key={self.anon_key[:8]}…, key={self.vault_key})"
