# Generated by Django 5.0.1 on 2026-03-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceMapRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(db_index=True, max_length=120, unique=True)),
                ('service_name', models.CharField(max_length=255)),
                ('portal', models.CharField(max_length=120)),
                ('version', models.CharField(max_length=20)),
                ('last_surveyed', models.DateTimeField()),
                ('surveyor_confidence', models.FloatField()),
                ('file_path', models.CharField(max_length=512)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Map',
                'verbose_name_plural': 'Service Maps',
                'ordering': ['-last_surveyed'],
            },
        ),
    ]
